/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scorereader;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.bytedeco.javacpp.opencv_core;
import static org.bytedeco.javacpp.opencv_imgproc.cvDilate;
import static org.bytedeco.javacpp.opencv_imgproc.cvErode;
import scorereader.components.images.ScrollDemo;

/**
 *
 * @author ascarneiro
 */
public class Editor extends javax.swing.JFrame {

    private ScrollDemo editor = new ScrollDemo();
    private opencv_core.IplImage imagemSemAlteracoes = null;
    private opencv_core.IplImage imagemEdicao = null;

    /**
     * Creates new form Editor
     */
    public Editor(opencv_core.IplImage image) {
        initComponents();
        this.imagemSemAlteracoes = image;
        editor.setOpaque(true);
        BufferedImage IplImageToBufferedImage = Utilities.IplImageToBufferedImage(imagemSemAlteracoes);
        editor.addImagem(new ImageIcon(Utilities.bufferedImageToByteArray(IplImageToBufferedImage)), true);
        containerEditor.add(editor);
        editor.repaint();
        containerEditor.repaint();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        containerEditor = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        ERODE_SL = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DILATE_SL = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        DILATAR = new javax.swing.JSpinner();
        ERODIR = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de imagem");

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        containerEditor.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setBottomComponent(containerEditor);

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ERODE_SL.setValue(0);
        ERODE_SL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ERODE_SLStateChanged(evt);
            }
        });
        menu.add(ERODE_SL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 630, -1));

        jLabel1.setText("Erodir:");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Dilatar");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        DILATE_SL.setValue(0);
        DILATE_SL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DILATE_SLStateChanged(evt);
            }
        });
        menu.add(DILATE_SL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 630, -1));

        jButton1.setText("Buscar contornos");
        menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, -1));

        DILATAR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DILATARStateChanged(evt);
            }
        });
        menu.add(DILATAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, -1));

        ERODIR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ERODIRStateChanged(evt);
            }
        });
        menu.add(ERODIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, -1));

        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));

        jButton3.setText("Remover linhas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 120, -1));

        jSplitPane1.setTopComponent(menu);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ERODE_SLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ERODE_SLStateChanged
        ERODIR.setValue(ERODE_SL.getValue());
    }//GEN-LAST:event_ERODE_SLStateChanged

    private void DILATE_SLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DILATE_SLStateChanged
        DILATAR.setValue(DILATE_SL.getValue());
    }//GEN-LAST:event_DILATE_SLStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        imagemSemAlteracoes = imagemEdicao;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ERODIRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ERODIRStateChanged
        Thread t = new Thread() {

            @Override
            public void run() {
                imagemEdicao = imagemSemAlteracoes.clone();
                cvErode(imagemEdicao, imagemEdicao, null, ERODE_SL.getValue());
                BufferedImage IplImageToBufferedImage = Utilities.IplImageToBufferedImage(imagemEdicao);
                editor.atualizarImagem(new ImageIcon(Utilities.bufferedImageToByteArray(IplImageToBufferedImage)), true);
            }
        };
        t.start();

    }//GEN-LAST:event_ERODIRStateChanged

    private void DILATARStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DILATARStateChanged

        Thread t = new Thread() {

            @Override
            public void run() {
                imagemEdicao = imagemSemAlteracoes.clone();
                cvDilate(imagemEdicao, imagemEdicao, null, Integer.valueOf(DILATAR.getValue().toString()));
                BufferedImage IplImageToBufferedImage = Utilities.IplImageToBufferedImage(imagemEdicao);
                editor.atualizarImagem(new ImageIcon(Utilities.bufferedImageToByteArray(IplImageToBufferedImage)), true);
            }

        };
        t.start();

    }//GEN-LAST:event_DILATARStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Thread t = new Thread() {

            @Override
            public void run() {
                try {
                    imagemSemAlteracoes = imagemSemAlteracoes.clone();
                    Utilities.removerLinhasDaPauta(
                            Utilities.bufferedImageToByteArray(
                                    Utilities.IplImageToBufferedImage(imagemSemAlteracoes.clone())));

                    String path = "C:\\Users\\ascarneiro\\Desktop\\TCC\\ScoreReader\\repository\\staffless.png";
                    BufferedImage read = ImageIO.read(new File(path));
                    imagemSemAlteracoes = Utilities.bufferedImageToIplImage(Utilities.bufferedImageToByteArray(read));
                    editor.atualizarImagem(new ImageIcon(Utilities.bufferedImageToByteArray(read)), true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        t.start();

    }//GEN-LAST:event_jButton3ActionPerformed

    public opencv_core.IplImage getImagemAlterada() {
        return imagemSemAlteracoes;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner DILATAR;
    private javax.swing.JSlider DILATE_SL;
    private javax.swing.JSlider ERODE_SL;
    private javax.swing.JSpinner ERODIR;
    private javax.swing.JPanel containerEditor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
