/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scorereader;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import scorereader.components.list.FiguraRenderer;
import scorereader.structure.Figura;

/**
 *
 * @author ascarneiro
 */
public class Rotulador extends javax.swing.JFrame {

    public static int width = 350;
    public static int height = 200;

    private String selecionado = "Seminima";
    private ArrayList<Figura> rotular = new ArrayList<Figura>();
    private ArrayList<Figura> semibreve = new ArrayList<Figura>();
    private ArrayList<Figura> minimas = new ArrayList<Figura>();
    private ArrayList<Figura> seminimas = new ArrayList<Figura>();
    private ArrayList<Figura> colcheias = new ArrayList<Figura>();
    private ArrayList<Figura> barraCompasso = new ArrayList<Figura>();
    private ArrayList<Figura> pausaSemibreve = new ArrayList<Figura>();
    private ArrayList<Figura> pausaMinima = new ArrayList<Figura>();
    private ArrayList<Figura> pausaSeminima = new ArrayList<Figura>();
    private ArrayList<Figura> pausaColcheia = new ArrayList<Figura>();
    private ArrayList<Figura> claveSol = new ArrayList<Figura>();
    private ArrayList<Figura> claveFa = new ArrayList<Figura>();
    private ArrayList<Figura> claveDo = new ArrayList<Figura>();
    private ArrayList<Figura> sustenidos = new ArrayList<Figura>();
    private ArrayList<Figura> bemois = new ArrayList<Figura>();
    private JList<Figura> rotularJL;
    private JList<Figura> semibreveJL;
    private JList<Figura> minimasJL;
    private JList<Figura> seminimasJL;
    private JList<Figura> colcheiasJL;
    private JList<Figura> barraCompassoJL;
    private JList<Figura> sustenidosJL;
    private JList<Figura> bemoisJL;

    private JList<Figura> pausaSemibreveJL;
    private JList<Figura> pausaMinimaJL;
    private JList<Figura> pausaSeminimaJL;
    private JList<Figura> pausaColcheiaJL;
    private JList<Figura> claveSolJL;
    private JList<Figura> claveFaJL;
    private JList<Figura> claveDoJL;

    /**
     * Creates new form Rotulador
     */
    public Rotulador(ArrayList<Figura> rotular) {
        this.rotular = rotular;
        initComponents();
        rotularJL = getJlist(rotular);
        semibreveJL = getJlist(semibreve);
        minimasJL = getJlist(minimas);
        seminimasJL = getJlist(seminimas);
        colcheiasJL = getJlist(colcheias);
        barraCompassoJL = getJlist(barraCompasso);
        barraCompassoJL = getJlist(barraCompasso);
        sustenidosJL = getJlist(sustenidos);
        bemoisJL = getJlist(bemois);
        pausaSemibreveJL = getJlist(pausaSemibreve);
        pausaMinimaJL = getJlist(pausaMinima);
        pausaSeminimaJL = getJlist(pausaSeminima);
        pausaColcheiaJL = getJlist(pausaColcheia);
        claveSolJL = getJlist(claveSol);
        claveFaJL = getJlist(claveFa);
        claveDoJL = getJlist(claveDo);

        ROTULAR_P.add(createMainPanel(rotularJL));
        SEMIBREVE_P.add(createMainPanel(semibreveJL));
        MINIMAS_P.add(createMainPanel(minimasJL));
        SEMINIMAS_P.add(createMainPanel(seminimasJL));
        COLCHEIAS_P.add(createMainPanel(colcheiasJL));
        BARRA_COMPASSO_P.add(createMainPanel(barraCompassoJL));
        PAUSA_SEMIBREVE_P.add(createMainPanel(pausaSemibreveJL));
        PAUSA_MINIMA_P.add(createMainPanel(pausaMinimaJL));
        PAUSA_SEMINIMA_P.add(createMainPanel(pausaSeminimaJL));
        PAUSA_COLCHEIA_P.add(createMainPanel(pausaColcheiaJL));
        CLAVE_SOL_P.add(createMainPanel(claveSolJL));
        CLAVE_FA_P.add(createMainPanel(claveFaJL));
        CLAVE_DO_P.add(createMainPanel(claveDoJL));
        SUSTENIDOS_P.add(createMainPanel(sustenidosJL));
        BEMOIS_P.add(createMainPanel(bemoisJL));

        SEMINIMA.requestFocus();
        setSelecionado(SEMINIMA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        SEMIBREVE = new javax.swing.JButton();
        SEMINIMA = new javax.swing.JButton();
        CLAVE_SOL = new javax.swing.JButton();
        MINIMA = new javax.swing.JButton();
        COLCHEIA = new javax.swing.JButton();
        SEMICOLCHEIA = new javax.swing.JButton();
        BARRA_COMPASSO = new javax.swing.JButton();
        CLAVE_FA = new javax.swing.JButton();
        REMOVER = new javax.swing.JButton();
        IE_PAUSA = new javax.swing.JCheckBox();
        SELECIONANDO = new javax.swing.JLabel();
        CLAVE_DO = new javax.swing.JButton();
        ADICIONAR = new javax.swing.JButton();
        SUSTENIDOS = new javax.swing.JButton();
        BEMOIS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Container = new javax.swing.JPanel();
        ROTULAR_P = new javax.swing.JPanel();
        SEMINIMAS_P = new javax.swing.JPanel();
        COLCHEIAS_P = new javax.swing.JPanel();
        BARRA_COMPASSO_P = new javax.swing.JPanel();
        MINIMAS_P = new javax.swing.JPanel();
        SUSTENIDOS_P = new javax.swing.JPanel();
        BEMOIS_P = new javax.swing.JPanel();
        CLAVE_SOL_P = new javax.swing.JPanel();
        CLAVE_FA_P = new javax.swing.JPanel();
        CLAVE_DO_P = new javax.swing.JPanel();
        SEMIBREVE_P = new javax.swing.JPanel();
        PAUSA_SEMIBREVE_P = new javax.swing.JPanel();
        PAUSA_MINIMA_P = new javax.swing.JPanel();
        PAUSA_SEMINIMA_P = new javax.swing.JPanel();
        PAUSA_COLCHEIA_P = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SEMIBREVE.setText("Semibreve");
        SEMIBREVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMIBREVEActionPerformed(evt);
            }
        });
        jPanel1.add(SEMIBREVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 33));

        SEMINIMA.setText("Seminima");
        SEMINIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMINIMAActionPerformed(evt);
            }
        });
        jPanel1.add(SEMINIMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 110, 33));

        CLAVE_SOL.setText("Clave Sol");
        CLAVE_SOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLAVE_SOLActionPerformed(evt);
            }
        });
        jPanel1.add(CLAVE_SOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 120, 33));

        MINIMA.setText("Minima");
        MINIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINIMAActionPerformed(evt);
            }
        });
        jPanel1.add(MINIMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, 33));

        COLCHEIA.setText("Colcheia");
        COLCHEIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLCHEIAActionPerformed(evt);
            }
        });
        jPanel1.add(COLCHEIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, 33));

        SEMICOLCHEIA.setText("Semi Colcheia");
        SEMICOLCHEIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMICOLCHEIAActionPerformed(evt);
            }
        });
        jPanel1.add(SEMICOLCHEIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 120, 33));

        BARRA_COMPASSO.setText("Barra compasso");
        BARRA_COMPASSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARRA_COMPASSOActionPerformed(evt);
            }
        });
        jPanel1.add(BARRA_COMPASSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 110, 33));

        CLAVE_FA.setText("Clave Fa");
        CLAVE_FA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLAVE_FAActionPerformed(evt);
            }
        });
        jPanel1.add(CLAVE_FA, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 110, 33));

        REMOVER.setText("Remover");
        jPanel1.add(REMOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 120, 33));

        IE_PAUSA.setText("Pausa");
        jPanel1.add(IE_PAUSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        SELECIONANDO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SELECIONANDO.setText("Selecionando: Semibreve");
        jPanel1.add(SELECIONANDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, -1));

        CLAVE_DO.setText("Clave Do");
        CLAVE_DO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLAVE_DOActionPerformed(evt);
            }
        });
        jPanel1.add(CLAVE_DO, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 120, 33));

        ADICIONAR.setText("Adicionar");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });
        jPanel1.add(ADICIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 120, 33));

        SUSTENIDOS.setText("Sustenidos");
        SUSTENIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUSTENIDOSActionPerformed(evt);
            }
        });
        jPanel1.add(SUSTENIDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, 33));

        BEMOIS.setText("Bemois");
        BEMOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEMOISActionPerformed(evt);
            }
        });
        jPanel1.add(BEMOIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 120, 33));

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Container.setMaximumSize(new java.awt.Dimension(10, 10));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ROTULAR_P.setBackground(new java.awt.Color(255, 255, 255));
        ROTULAR_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rotular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        ROTULAR_P.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ROTULAR_P.setMaximumSize(new java.awt.Dimension(10, 10));
        ROTULAR_P.setOpaque(false);
        ROTULAR_P.setPreferredSize(new java.awt.Dimension(10, 10));
        ROTULAR_P.setLayout(new java.awt.BorderLayout());
        Container.add(ROTULAR_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 390));

        SEMINIMAS_P.setBackground(new java.awt.Color(255, 255, 255));
        SEMINIMAS_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semimas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        SEMINIMAS_P.setMaximumSize(new java.awt.Dimension(10, 10));
        SEMINIMAS_P.setOpaque(false);
        SEMINIMAS_P.setPreferredSize(new java.awt.Dimension(10, 10));
        SEMINIMAS_P.setLayout(new java.awt.BorderLayout());
        Container.add(SEMINIMAS_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 210, 340));

        COLCHEIAS_P.setBackground(new java.awt.Color(255, 255, 255));
        COLCHEIAS_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colcheias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        COLCHEIAS_P.setMaximumSize(new java.awt.Dimension(5, 5));
        COLCHEIAS_P.setMinimumSize(new java.awt.Dimension(5, 5));
        COLCHEIAS_P.setOpaque(false);
        COLCHEIAS_P.setPreferredSize(new java.awt.Dimension(5, 5));
        COLCHEIAS_P.setLayout(new java.awt.BorderLayout());
        Container.add(COLCHEIAS_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 210, 340));

        BARRA_COMPASSO_P.setBackground(new java.awt.Color(255, 255, 255));
        BARRA_COMPASSO_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barra Compasso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        BARRA_COMPASSO_P.setMaximumSize(new java.awt.Dimension(5, 5));
        BARRA_COMPASSO_P.setMinimumSize(new java.awt.Dimension(5, 5));
        BARRA_COMPASSO_P.setOpaque(false);
        BARRA_COMPASSO_P.setPreferredSize(new java.awt.Dimension(5, 5));
        BARRA_COMPASSO_P.setLayout(new java.awt.BorderLayout());
        Container.add(BARRA_COMPASSO_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, 210, 340));

        MINIMAS_P.setBackground(new java.awt.Color(255, 255, 255));
        MINIMAS_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Minimas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        MINIMAS_P.setMaximumSize(new java.awt.Dimension(10, 10));
        MINIMAS_P.setOpaque(false);
        MINIMAS_P.setPreferredSize(new java.awt.Dimension(10, 10));
        MINIMAS_P.setLayout(new java.awt.BorderLayout());
        Container.add(MINIMAS_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, 340));

        SUSTENIDOS_P.setBackground(new java.awt.Color(255, 255, 255));
        SUSTENIDOS_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sustenidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        SUSTENIDOS_P.setMaximumSize(new java.awt.Dimension(5, 5));
        SUSTENIDOS_P.setMinimumSize(new java.awt.Dimension(5, 5));
        SUSTENIDOS_P.setOpaque(false);
        SUSTENIDOS_P.setPreferredSize(new java.awt.Dimension(5, 5));
        SUSTENIDOS_P.setLayout(new java.awt.BorderLayout());
        Container.add(SUSTENIDOS_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, 210, 340));

        BEMOIS_P.setBackground(new java.awt.Color(255, 255, 255));
        BEMOIS_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bemois", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        BEMOIS_P.setMaximumSize(new java.awt.Dimension(5, 5));
        BEMOIS_P.setMinimumSize(new java.awt.Dimension(5, 5));
        BEMOIS_P.setOpaque(false);
        BEMOIS_P.setPreferredSize(new java.awt.Dimension(5, 5));
        BEMOIS_P.setLayout(new java.awt.BorderLayout());
        Container.add(BEMOIS_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 390, 210, 340));

        CLAVE_SOL_P.setBackground(new java.awt.Color(255, 255, 255));
        CLAVE_SOL_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clave Sol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        CLAVE_SOL_P.setMaximumSize(new java.awt.Dimension(5, 5));
        CLAVE_SOL_P.setMinimumSize(new java.awt.Dimension(5, 5));
        CLAVE_SOL_P.setOpaque(false);
        CLAVE_SOL_P.setPreferredSize(new java.awt.Dimension(5, 5));
        CLAVE_SOL_P.setLayout(new java.awt.BorderLayout());
        Container.add(CLAVE_SOL_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 730, 210, 340));

        CLAVE_FA_P.setBackground(new java.awt.Color(255, 255, 255));
        CLAVE_FA_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clave Fa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        CLAVE_FA_P.setMaximumSize(new java.awt.Dimension(5, 5));
        CLAVE_FA_P.setMinimumSize(new java.awt.Dimension(5, 5));
        CLAVE_FA_P.setOpaque(false);
        CLAVE_FA_P.setPreferredSize(new java.awt.Dimension(5, 5));
        CLAVE_FA_P.setLayout(new java.awt.BorderLayout());
        Container.add(CLAVE_FA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 730, 210, 340));

        CLAVE_DO_P.setBackground(new java.awt.Color(255, 255, 255));
        CLAVE_DO_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clave Do", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        CLAVE_DO_P.setMaximumSize(new java.awt.Dimension(5, 5));
        CLAVE_DO_P.setMinimumSize(new java.awt.Dimension(5, 5));
        CLAVE_DO_P.setOpaque(false);
        CLAVE_DO_P.setPreferredSize(new java.awt.Dimension(5, 5));
        CLAVE_DO_P.setLayout(new java.awt.BorderLayout());
        Container.add(CLAVE_DO_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 730, 210, 340));

        SEMIBREVE_P.setBackground(new java.awt.Color(255, 255, 255));
        SEMIBREVE_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semibreve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        SEMIBREVE_P.setMaximumSize(new java.awt.Dimension(10, 10));
        SEMIBREVE_P.setOpaque(false);
        SEMIBREVE_P.setPreferredSize(new java.awt.Dimension(10, 10));
        SEMIBREVE_P.setLayout(new java.awt.BorderLayout());
        Container.add(SEMIBREVE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 340));

        PAUSA_SEMIBREVE_P.setBackground(new java.awt.Color(255, 255, 255));
        PAUSA_SEMIBREVE_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pausa Semiberve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        PAUSA_SEMIBREVE_P.setMaximumSize(new java.awt.Dimension(10, 10));
        PAUSA_SEMIBREVE_P.setOpaque(false);
        PAUSA_SEMIBREVE_P.setPreferredSize(new java.awt.Dimension(10, 10));
        PAUSA_SEMIBREVE_P.setLayout(new java.awt.BorderLayout());
        Container.add(PAUSA_SEMIBREVE_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 210, 340));

        PAUSA_MINIMA_P.setBackground(new java.awt.Color(255, 255, 255));
        PAUSA_MINIMA_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pausa Minima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        PAUSA_MINIMA_P.setMaximumSize(new java.awt.Dimension(10, 10));
        PAUSA_MINIMA_P.setOpaque(false);
        PAUSA_MINIMA_P.setPreferredSize(new java.awt.Dimension(10, 10));
        PAUSA_MINIMA_P.setLayout(new java.awt.BorderLayout());
        Container.add(PAUSA_MINIMA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 730, 210, 340));

        PAUSA_SEMINIMA_P.setBackground(new java.awt.Color(255, 255, 255));
        PAUSA_SEMINIMA_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pausa Seminima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        PAUSA_SEMINIMA_P.setMaximumSize(new java.awt.Dimension(10, 10));
        PAUSA_SEMINIMA_P.setOpaque(false);
        PAUSA_SEMINIMA_P.setPreferredSize(new java.awt.Dimension(10, 10));
        PAUSA_SEMINIMA_P.setLayout(new java.awt.BorderLayout());
        Container.add(PAUSA_SEMINIMA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 730, 200, 340));

        PAUSA_COLCHEIA_P.setBackground(new java.awt.Color(255, 255, 255));
        PAUSA_COLCHEIA_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pausa Colcheia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        PAUSA_COLCHEIA_P.setMaximumSize(new java.awt.Dimension(10, 10));
        PAUSA_COLCHEIA_P.setOpaque(false);
        PAUSA_COLCHEIA_P.setPreferredSize(new java.awt.Dimension(10, 10));
        PAUSA_COLCHEIA_P.setLayout(new java.awt.BorderLayout());
        Container.add(PAUSA_COLCHEIA_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 730, 210, 340));

        jScrollPane3.setViewportView(Container);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COLCHEIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLCHEIAActionPerformed
        setSelecionado(COLCHEIA);
    }//GEN-LAST:event_COLCHEIAActionPerformed

    private void SEMIBREVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMIBREVEActionPerformed
        setSelecionado(SEMIBREVE);
    }//GEN-LAST:event_SEMIBREVEActionPerformed

    private void MINIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINIMAActionPerformed
        setSelecionado(MINIMA);
    }//GEN-LAST:event_MINIMAActionPerformed

    private void SEMINIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMINIMAActionPerformed
        setSelecionado(SEMINIMA);
    }//GEN-LAST:event_SEMINIMAActionPerformed

    private void SEMICOLCHEIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMICOLCHEIAActionPerformed
        setSelecionado(SEMICOLCHEIA);
    }//GEN-LAST:event_SEMICOLCHEIAActionPerformed

    private void BARRA_COMPASSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BARRA_COMPASSOActionPerformed
        setSelecionado(BARRA_COMPASSO);
    }//GEN-LAST:event_BARRA_COMPASSOActionPerformed

    private void CLAVE_SOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLAVE_SOLActionPerformed
        setSelecionado(CLAVE_SOL);
    }//GEN-LAST:event_CLAVE_SOLActionPerformed

    private void CLAVE_FAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLAVE_FAActionPerformed
        setSelecionado(CLAVE_FA);
    }//GEN-LAST:event_CLAVE_FAActionPerformed

    private void CLAVE_DOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLAVE_DOActionPerformed
        setSelecionado(CLAVE_DO);
    }//GEN-LAST:event_CLAVE_DOActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed

        List<Figura> selecionados = getSelecionadosRotular();
        if (selecionado.equalsIgnoreCase("Semibreve")) {
        } else if (selecionado.equalsIgnoreCase("Minima")) {
            minimas.addAll(selecionados);
            recarregar(minimas, minimasJL);
        } else if (selecionado.equalsIgnoreCase("Seminima")) {
            seminimas.addAll(selecionados);
            recarregar(seminimas, seminimasJL);
        } else if (selecionado.equalsIgnoreCase("Colcheia")) {
            colcheias.addAll(colcheias);
            recarregar(colcheias, colcheiasJL);
        } else if (selecionado.equalsIgnoreCase("Semi Colcheia")) {
        } else if (selecionado.equalsIgnoreCase("Barra Compasso")) {
            barraCompasso.addAll(selecionados);
            recarregar(barraCompasso, barraCompassoJL);
        } else if (selecionado.equalsIgnoreCase("Clave Sol")) {
        } else if (selecionado.equalsIgnoreCase("Clave Fa")) {
        } else if (selecionado.equalsIgnoreCase("Clave Do")) {

        }

    }//GEN-LAST:event_ADICIONARActionPerformed

    private void SUSTENIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUSTENIDOSActionPerformed
        setSelecionado(SUSTENIDOS);
    }//GEN-LAST:event_SUSTENIDOSActionPerformed

    private void BEMOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEMOISActionPerformed
        setSelecionado(BEMOIS);
    }//GEN-LAST:event_BEMOISActionPerformed

    public void setSelecionado(JButton jb) {
        this.selecionado = jb.getText();
        SELECIONANDO.setText("Selecionando: " + jb.getText());
    }

    private JList getJlist(ArrayList<Figura> figuras) {
        return createListFiguras(figuras);
    }

    private JPanel createMainPanel(JList lista) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        // create list book and set to scrollpane and add to panel
        panel.add(new JScrollPane(lista),
                BorderLayout.CENTER);
        return panel;
    }

    private void recarregar(ArrayList<Figura> figuras, JList lista) {
        DefaultListModel<Figura> model = new DefaultListModel<>();

        for (Figura figura : figuras) {
            model.addElement(figura);
        }
        lista.setModel(model);
        lista.repaint();
        lista.updateUI();
    }

    private JList<Figura> createListFiguras(ArrayList<Figura> figuras) {
        // create List model
        DefaultListModel<Figura> model = new DefaultListModel<>();

        for (Figura figura : figuras) {
            model.addElement(figura);
        }

        // create JList with model
        JList<Figura> list = new JList<Figura>(model);
        list.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        list.setVisibleRowCount(-1);
        // set cell renderer
        list.setCellRenderer(new FiguraRenderer());
        return list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton BARRA_COMPASSO;
    private javax.swing.JPanel BARRA_COMPASSO_P;
    private javax.swing.JButton BEMOIS;
    private javax.swing.JPanel BEMOIS_P;
    private javax.swing.JButton CLAVE_DO;
    private javax.swing.JPanel CLAVE_DO_P;
    private javax.swing.JButton CLAVE_FA;
    private javax.swing.JPanel CLAVE_FA_P;
    private javax.swing.JButton CLAVE_SOL;
    private javax.swing.JPanel CLAVE_SOL_P;
    private javax.swing.JButton COLCHEIA;
    private javax.swing.JPanel COLCHEIAS_P;
    private javax.swing.JPanel Container;
    private javax.swing.JCheckBox IE_PAUSA;
    private javax.swing.JButton MINIMA;
    private javax.swing.JPanel MINIMAS_P;
    private javax.swing.JPanel PAUSA_COLCHEIA_P;
    private javax.swing.JPanel PAUSA_MINIMA_P;
    private javax.swing.JPanel PAUSA_SEMIBREVE_P;
    private javax.swing.JPanel PAUSA_SEMINIMA_P;
    private javax.swing.JButton REMOVER;
    private javax.swing.JPanel ROTULAR_P;
    private javax.swing.JLabel SELECIONANDO;
    private javax.swing.JButton SEMIBREVE;
    private javax.swing.JPanel SEMIBREVE_P;
    private javax.swing.JButton SEMICOLCHEIA;
    private javax.swing.JButton SEMINIMA;
    private javax.swing.JPanel SEMINIMAS_P;
    private javax.swing.JButton SUSTENIDOS;
    private javax.swing.JPanel SUSTENIDOS_P;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private List<Figura> getSelecionadosRotular() {
        List<Figura> selecionados = rotularJL.getSelectedValuesList();
        for (Figura s : selecionados) {
            rotular.remove(s);
        }
        recarregar(rotular, rotularJL);
        return selecionados;
    }
}
